version: "3.8"

services:
  bilet-satin-alma:
    build: .
    container_name: bilet_satin_alma
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - TZ=Europe/Istanbul
