version: "3.8"

services:
  php-apache:
    build: .
    container_name: bilet_satin_alma
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./db:/var/www/html/db
    environment:
      - TZ=Europe/Istanbul
